import pygame

# Pygame initialization
pygame.init()
pygame.font.init()

# Define the background colour using RGB color coding
background_colour = (255, 255, 255)
header_colour = (192, 192, 192)  # Gray color for the header

# Define the dimensions of the screen object (width, height)
screen_width = 1440
screen_height = 950
screen = pygame.display.set_mode((screen_width, screen_height))

# Set the caption of the screen
pygame.display.set_caption('Optimochrone')

# Fill the background colour to the screen
screen.fill(background_colour)

# Set up the font
font = pygame.font.Font(None, 28)

# Render the header text
header_text = font.render('Optimochrone', True, pygame.Color('black'))

# Calculate the position to align the header text at the top-left
header_x = 0
header_y = 0

# Calculate the dimensions of the header based on the text size
header_width = screen_width
header_height = 40

# Draw the header rectangle with the gray color
header_rect = pygame.Rect(header_x, header_y, header_width, header_height)
pygame.draw.rect(screen, header_colour, header_rect)

# Blit the header text onto the screen
screen.blit(header_text, (header_x + 10, header_y + 10))

# Load the image of the cycloid curve
curve_image = pygame.image.load('cycloid_curve3.png')

# Get the dimensions of the curve image
curve_image_width = curve_image.get_width()
curve_image_height = curve_image.get_height()

# Calculate the position to align the image on the right side
image_x = screen_width - curve_image_width - 25
image_y = header_y + header_height + 25

# Blit the curve image onto the screen
screen.blit(curve_image, (image_x, image_y))

# Cycloid curve information
curve_info = [
    "                                                                                                 Default Graph       Custom Graph        Learn More",
    "   ",
    "           Cycloid Curve",
    "           -----------------",
    "           Cycloid, the curve generated by a point on the circumference of a circle that rolls along a ",
    "           straight line.",
    "           It is traced by a point on the circumference of a rolling circle.",
     "     ",
    "           If r is the radius of the circle and θ (theta) is the angular displacement of the circle, then the equations for a cycloid curve are:",
    "     ",
    "     ",
    "           x = r(t - sin(t))",
    "           y = r(1 - cos(t))",
    "     ",
    "     ",
    "           r = radius",
    "           t = theta",
    "     ",
    "           The points of the curve that touch the straight line are separated along the line by a distance equal to 2πr,",
    "           which is the circumference of the circle, indicating one complete revolution of the circle.",
    "           The curve is periodic, which means that it repeats in an identical pattern for each cycle, or length of the line, that is equal to 2πr.",
    "         ",
    "           The length of one arch of the cycloid curve is 8r.",
    "           Applications of the cycloid curve include gear design and pendulum motion.",
]

# Calculate the position to align the text on the left side
text_x = header_x
text_y = image_y

# Render the text on separate surfaces
text_surfaces = []
for line in curve_info:
    text_surface = font.render(line, True, pygame.Color('black'))
    text_surfaces.append(text_surface)

# Blit the text surfaces onto the screen
for text_surface in text_surfaces:
    screen.blit(text_surface, (text_x, text_y))
    text_y += text_surface.get_height() + 10

# Update the display using flip
pygame.display.flip()

# Variable to keep our game loop running
running = True

# Game loop
while running:
    # For loop through the event queue
    for event in pygame.event.get():
        # Check for QUIT event
        if event.type == pygame.QUIT:
            running = False

# Exit Pygame
pygame.quit()
